version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64

  proxy:
      image: bref/local-api-gateway
      ports: 
        - "8080:8000"
      environment:
          TARGET: "app:8080"